kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealed-secrets-manager
rules:
- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets"]
  verbs: ["get", "create", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-sealed-secrets
  namespace: ivana-openfaas-fn
subjects:
- kind: Group
  name: system:serviceaccounts:ivana-openfaas-fn
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sealed-secrets-manager
  apiGroup: rbac.authorization.k8s.io