apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: of-router
  namespace: ivana-openfaas
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: of-router
    spec:
      containers:
      - name: of-router
        image: openfaas/cloud-router:0.5.1
        imagePullPolicy: Always
        env:
          - name: upstream_url
            value: "http://gateway.ivana-openfaas:8080"
          - name: port
            value: "8080"
          - name: timeout
            value: "60s"
# For OAuth 2.0
          - name: auth_url
            value: "http://auth.ivana-openfaas:8080"
# For no OAuth 2.0
          # - name: auth_url
          #   value: "http://echo.openfaas:8080"
        ports:
        - containerPort: 8080
          protocol: TCP

